### ISSUE TITLE
Handle GOES-16 Full Disc images

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#1008]
GOES-16 full disk images use the `Geostationary` projection and claim to follow CF. However, the [CF specification](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_geostationary_projection) states that the mapping coordinates must be in radians, whereas GOES-16 stores them in microradians.

I've started [updating](https://github.com/lesserwhirls/thredds/tree/notSoCf) the projection and transform to handle this not-so-cf-y-ness and is a work in progress. This work is being done on `4.6` and should transfer to 5.0 cleanly.

Example files: any of [these](http://thredds-test.unidata.ucar.edu/thredds/catalog/satellite/goes16/GOES16/FullDisk/catalog.html) will do.

**Comment by ethanrd** [comment]
CF standard names have canonical units which means any units may be used as long as the units used are convertible to the canonical units.

If I'm interpreting the CF Geostationary projection [section](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_geostationary_projection) correctly, it is redefining the units for variables with standard names `projection_x_coordinate` and `projection_y_coordinate` from meters (`m`) to radians. Unfortunately, it says "their units are radians" rather than "their canonical units are radians".

I think that text should probably be updated to specify "canonical units" not just "units". I will email the CF list to see what others there think.

**Comment by lesserwhirls** [comment]
Cool, thanks @ethanrd! BTW - these changes allow the GOES-16 data to be geo-referenced properly in ToolsUI. Just need to add some tests.

**Comment by lesserwhirls** [comment]
Fixed in Unidata/thredds#1023
