### ISSUE TITLE
GridDataset thread safe issue

### ISSUE THREAD

**Issue by sefadolunay** [Unidata/thredds#1037]
Hi,
I am trying to read grib1 data by using _GridDataset_ and _GeoGrid_ classes. However _GridDataset_ is not thread safe thus I am unable to read a large file with multi-threading. As a result this causes performance issues. Is it possible to make this class thread safe or is there a way to read so that multiple threads can read the same file at the same time without synchronization?
(I am using netcdf-java 4.6.11)
Thank you.

**Comment by cwardgar** [comment]
Hi @sefadolunay. `GridDataset` is not thread-safe because the underlying `java.io.RandomAccessFile` is not thread safe. The difficulty is the you need to make two calls to `RandomAccessFile` to read anything: `seek()`, and then `read()`. If you don't synchronize, then one thread could `seek()`, the next thread could `seek()`, then thread 1 could `read()`, and then thread 2 could `read()`. Both threads would get the wrong data.

This limitation applies to all dataset classes in NetCDF-Java, including `NetcdfFile` and `NetcdfDataset`: they are not thread-safe unless externally synchronized. `GridDataset` wraps `NetcdfDataset`.

So, we've established that multiple threads cannot _share_ a single `GridDataset` object. However, there's nothing stopping you from creating a distinct `GridDataset` object in each thread. They will have different `RandomAccessFile`s that won't interfere with each other. However, I struggle to see the utility of that. In general, multi-threaded reads of a large file are no faster than single-threaded reads, because the operation is obviously IO-bound. Adding threads won't magically improve your disk's performance.

**Comment by sefadolunay** [comment]
Thank you for your answer @cwardgar. I also observed that it was due to `java.io.RandomAccessFile`. 

Establishment of a new `GridDataset` object for each thread consumes time so it seems reasonable to make an object pool for them, I think. So each thread can grab an already opened `GridDataset` and releases it when it finishes its job?

We are using RAID disks for file storage, so I hope to see a considerable performance improvement with multi-threaded reads.

**Comment by cwardgar** [comment]
> Establishment of a new GridDataset object for each thread consumes time so it seems reasonable 
> to make an object pool for them, I think. So each thread can grab an already opened GridDataset 
> and releases it when it finishes its job?

It's interesting that you mention this, because we actually have a very [similar facility](https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/Caching.html) (grep for "Object Caching"). Our results have been mixed, and we're not sure that the performance improvement justifies the additional complexity (it's been a frequent source of bugs).

As usual, the only way to know for sure is to benchmark. I'd be interested to hear your results, if you'd care to share them.
