### ISSUE TITLE
Aggregation typical dataset default is RANDOM

### ISSUE THREAD

**Issue by shane-axiom** [Unidata/thredds#111]
I was surprised to discover that aggregations by default use a random dataset from the aggregation as the typical dataset (source of attribute values, etc).

https://github.com/Unidata/thredds/blob/4.5.5/cdm/src/main/java/ucar/nc2/ncml/Aggregation.java#L531

TypicalDataset.LATEST seems like a much more intuitive default to me. Would it make sense to change this?

**Comment by cwardgar** [comment]
Hi Shane,

That comment is misleading. The default is actually PENULTIMATE [1]. We think that's better than LATEST because the latest dataset could still be getting written when we inspect it.

[1] https://github.com/Unidata/thredds/blob/4.5.5/tds/src/main/java/thredds/server/config/CdmInit.java#L144

Cheers,
Christian
