### ISSUE TITLE
Radar Server returns 500

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#235]
@dopplershift - I was just checking out logs on thredds.ucar.edu and I saw one case of the radar server returning a 500:

http://thredds.ucar.edu/thredds/dodsC/nexrad/level3/IDD/N0R/GYX/20151012/Level3_GYX_N0R_20151012_1441.nids.dds

```
Error {
    code = 500;
    message = "java.io.EOFException: Reading /data/ldm/pub/native/radar/level3/nexrad/N0R/GYX/20151012/Level3_GYX_N0R_20151012_1441.nids at 8194 file length = 8194";
};
```

**Comment by dopplershift** [comment]
MetPy doesn't complain when reading the file. I've attached the file here and will investigate when I get the chance.
[Level3_GYX_N0R_20151012_1441.nids | uploaded via ZenHub](https://files.zenhub.io/561bfaf73f6316ae5bed7e54)

**Comment by lesserwhirls** [comment]
Awesome - thanks for taking a look @dopplershift!

**Comment by dopplershift** [comment]
The problem is actually in the HDF4 IOSP `H4header.isValidFile`. It blows past the EOF looking for its magic bytes. It was introduced in a coverity fix commit (a2d4c), which changed the way the bytes were read; not having 4 bytes to read became an exception.

Easy fix is to make sure loop conditions account for needing the 4 bytes.
