### ISSUE TITLE
Possible level 2 RADAR IOSP error

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#248]
http://thredds.ucar.edu/thredds/dodsC/nexrad/level2/KDIX/20151020/Level2_KDIX_20151020_0832.ar2v.html

```
Error {
    code = 500;
    message = "java.nio.channels.ClosedChannelException";
};
```

**Comment by dopplershift** [comment]
Looks like a corrupted file, but I'll dig in further to see what's up. Also blows up MetPy's Level2 reader. Not clear yet if there's anything better the IOSP/Python code could do better.

[Level2_KDIX_20151020_0832.ar2v | uploaded via ZenHub](https://files.zenhub.io/5627ba6788bd18e23150f9b3)

**Comment by dopplershift** [comment]
Should also be noted that the exact same file is on thredds-dev, so it would seem that this wasn't a case of a dropped chunk by one of our systems.

**Comment by dopplershift** [comment]
So, this is a problem with our ingest process. We assume volume names are unique out to the minute, but they aren't. So what happened was that a volume was started at 0832 and that first chunk went out. Then the volume was restarted (actually within the same second--full time is 083212), and the first chunk came out again.

The problem is that you end up with multiple volume headers, outside the expect compressed block structure. What should we be doing if it turns out the file is corrupt/invalid?

**Comment by dopplershift** [comment]
Resolved that 500 is the right code for a bad file on our end--we should just make sure to remove the problem file.
