### ISSUE TITLE
HTML templating

### ISSUE THREAD

**Issue by adamsteer** [Unidata/thredds#444]
This is pretty much a wish - relating to style rather than function. Is it possible to get thredds to use a HTML templating system? Being able to customise style sheets is great, but I can't yet see any way of gaining more control without becoming a Java developer. Yes, many clients just use machines to read our catalogs, but many actual humans come and look too.

**Comment by cwardgar** [comment]
This is a long-neglected deficiency of the TDS. Modern webapps use an MVC approach, where the model (the data displayed on the page), the view (the page layout and styling), and the controller (the logic that generates the response) are separate. This loose coupling enables HTML templating technologies to be used for the view component.

Currently, we're doing everything in the controller; there is no discrete model or view. [Here](https://github.com/Unidata/thredds/blob/5.0.0/tds/src/main/java/thredds/core/ConfigCatalogHtmlWriter.java#L126) is where we generate the HTML for catalogs. _Shudder_. JavaServer Pages addressed the problem of writing HTML in Java code in **1999**, but here we are.

I like [Thymeleaf](http://www.thymeleaf.org/) for this. It uses *natural templates*--HTML that can be correctly displayed in browsers and also work as static prototypes. Thymeleaf is the preferred template engine for Spring, so this won't be as much work as it would be otherwise.

**Comment by cwardgar** [comment]
It occurs to me that we're also generating a lot of XML from within Java as well, such as [here](https://github.com/Unidata/thredds/blob/5.0.0/cdm/src/main/java/ucar/nc2/ft/point/writer/FeatureDatasetCapabilitiesWriter.java). That seems bad as well. Luckily, [Thymeleaf can process XML input](http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#what-kind-of-templates-can-thymeleaf-process).

**Comment by DennisHeimbigner** [comment]
What web pages do we generate now?
I can think of: catalogs and ncss. What else? WMS?

**Comment by cwardgar** [comment]
We also generate TDS admin pages and OpenDAP forms in Java. The WMS pages are built by the edal-wms dependency.

**Comment by lesserwhirls** [comment]
Added in Unidata/thredds#1109 and Unidata/thredds#1110
