### ISSUE TITLE
Provide a way to tell which attribute it fails to parse when netCDF-java fails to parse OPeNDAP DAS

### ISSUE THREAD

**Issue by kyang2014** [Unidata/thredds#464]
For some use cases,  the Tools UI fails to parse the OPeNDAP DAS, it then disables the generation of the whole DAS.  It will be very useful for a user to know the exact error place that makes the netcdf-java ignore the DAS. 

An example, with tools UI 4.6, all the attributes of the following request is gone whereas

https://eosdap.hdfgroup.org:8080/opendap/data/test/kent/OMPS-NPP/OMPS-NPP_NMEV-L1B-p000_v2.0_2012m1025t061940_o05149_2016m0229t140028.h5

whereas you can find the DAS output here:
https://eosdap.hdfgroup.org:8080/opendap/data/test/kent/OMPS-NPP/OMPS-NPP_NMEV-L1B-p000_v2.0_2012m1025t061940_o05149_2016m0229t140028.h5.das

The ncdump of netCDF-C  can dump the attribute by using
ncdump -h https://eosdap.hdfgroup.org:8080/opendap/data/test/kent/OMPS-NPP/OMPS-NPP_NMEV-L1B-p000_v2.0_2012m1025t061940_o05149_2016m0229t140028.h5

**Comment by cwardgar** [comment]
This issue follows from an e-support ticket: [VGQ-678069](https://andy.unidata.ucar.edu/esupport/staff/index.php?_m=tickets&_a=viewticket&ticketid=26544).

**Comment by DennisHeimbigner** [comment]
At the moment, there is no way for a user to figure out what specific attribute caused the failure. This is because the DAS parser is not properly built to deal with this.
The same is true of the DDS parser. So, fixing it requires modifying the DAS (and DDS) parser to catch selected kinds of errors and save them for reporting after the parse is done. The issue is resources: fixing this is not high priority since bad attributes like this are not common. Sorry about that.  I will see if I can come up with some kind of kludge Real Soon Now.

=Dennis Heimbigner

**Comment by kyang2014** [comment]
Is it possible for you to quickly check the above example and tell me what may be wrong with this DAS?

**Comment by DennisHeimbigner** [comment]
Will do.

**Comment by DennisHeimbigner** [comment]
2 things:
1. The problem was a (dap)byte valued fill value of -127.
2. Did you look in the output (stack trace)? You should have seen a AttributeBadValueException that would give a clue.
3. Looked at the dap2 spec and I think technically, the -127 value should have been converted to +129;
    have modified the code to do this by keeping the same 8-bit  bit pattern.
Problem of better attribute failure reporting remains to be done.

**Comment by kyang2014** [comment]
Thanks, Dennis. This is the problem. The _FillValue should not be -127.  How did you get the stack trace and found the AttributeBadValueException?

**Comment by DennisHeimbigner** [comment]
I am now curious as to what happened to that stack trace. How did you run toolsUI?
From the command line e.g. java -jar ...ToolsUI ,...?

**Comment by kyang2014** [comment]
I am not a java guy,sorry for the ignorance.  I just downloaded ToolsUI and used the GUI interface of ToolsUI.


I will ToolsUI from the command-line.

Kent


________________________________

**Comment by DennisHeimbigner** [comment]
I assume you mean you just clicked on the ToolsUI jar to start it up, correct?

**Comment by kyang2014** [comment]
Dennis, 

Thanks a lot, running toolsUI from the command-line caught the _Fillvalue issue. I guess this method may be sufficient for me  to track the similar issue in the future. Thanks again.

**Comment by kyang2014** [comment]
I assume you mean you just clicked on the ToolsUI jar to start it up, correct?
----
Yes, that was what I always did.
