### ISSUE TITLE
Truncatation of lat/lon values results in bad bounding boxes on NCSS dataset webpage

### ISSUE THREAD

**Issue by kerfoot** [Unidata/thredds#470]
I think there's an issue with the calculation of the default bounding box that the user is presented on a NCSS data request webpage that results in 0 results.  In certain cases for Point datasets (and likely others), the default bounding box contained in the #bboxSubset div, does not contain lat/lon of the dataset.  See this example for a demonstration:

http://opendap-devel.ooi.rutgers.edu:8090/thredds/ncss/sandbox/8a8cc363-e1a5-42df-a5ef-cf107a61e3cc/deployment0001_GS01SUMO-RID16-04-VELPTA000-telemetered-velpt_ab_dcl_instrument.ncml/dataset.html

When I retrieve the lat and lon values for this dataset using the OPeNDAP data access page, both the lat and lon values are contstant:

http://opendap-devel.ooi.rutgers.edu:8090/thredds/dodsC/sandbox/8a8cc363-e1a5-42df-a5ef-cf107a61e3cc/deployment0001_GS01SUMO-RID16-04-VELPTA000-telemetered-velpt_ab_dcl_instrument.ncml.ascii?lat[0:1:13017],lon[0:1:13017]

In this particular case, the platform is located in the southern ocean at a latitude of -54.40833333333333 (yes, that's a precision of 14 decimal places); however, the southern latitude presented to the user via the NCSS data request page bounding box is: -54.408333, which is just North of -54.40833333333333, resulting in the bounding box **not** containing the actual platform.

If the user selects variables and does nothing to the bounding box, no data is pulled for the request:

http://opendap-devel.ooi.rutgers.edu:8090/thredds/ncss/sandbox/8a8cc363-e1a5-42df-a5ef-cf107a61e3cc/deployment0001_GS01SUMO-RID16-04-VELPTA000-telemetered-velpt_ab_dcl_instrument.ncml?req=point&var=velpt_ab_eastward_velocity&var=velpt_ab_northward_velocity&north=-54.407333&west=-89.357500&east=-89.356500&south=-54.408333&time_start=2014-11-14T10%3A36%3A42Z&time_end=2015-09-30T14%3A33%3A38Z&accept=csv

However, if I change the southern latitude value from -54.408333 to -54.08334, the response contains the information I requested:

http://opendap-devel.ooi.rutgers.edu:8090/thredds/ncss/sandbox/8a8cc363-e1a5-42df-a5ef-cf107a61e3cc/deployment0001_GS01SUMO-RID16-04-VELPTA000-telemetered-velpt_ab_dcl_instrument.ncml?req=point&var=velpt_ab_eastward_velocity&var=velpt_ab_northward_velocity&north=-54.407333&west=-89.357500&east=-89.356500&south=-54.408334&time_start=2014-11-14T10%3A36%3A42Z&time_end=2015-09-30T14%3A33%3A38Z&accept=csv

Looks like it's a precision issue that presents itself when a lat/lon measured, in decimal degrees does, not result in finite decimal precision.  I understand that the bounding box "initial extents are approximate", but the values should be calculated to ensure that the lat/lon of the Station is included in them.  Otherwise, the user gets a blank page when using the defaults and thinks something is wrong.

Assuming this is the issue, the fix might be the following, assuming lat/lons in decimal degrees:

1. The value used for the north extent should have a (small) positive decimal number added.
2. The value used for the south extent should have a (small) negative decimal number added.
3. The value used for the east extent should have a (small) positive decimal number added.
4. The value used for the west extent should have a (small) negative decimal number added.

**Comment by lesserwhirls** [comment]
Hi @kerfoot,

It looks like the issue is in `cdm/src/main/java/ucar/nc2/ft/point/writer/FeatureDatasetPointXML.java`:

```java
 private Element writeBoundingBox(LatLonRect bb) {
    Element bbElem = new Element("LatLonBox"); // from KML
    bbElem.addContent(new Element("west").addContent(ucar.unidata.util.Format.dfrac(bb.getLonMin(), 6)));
    bbElem.addContent(new Element("east").addContent(ucar.unidata.util.Format.dfrac(bb.getLonMax(), 6)));
    bbElem.addContent(new Element("south").addContent(ucar.unidata.util.Format.dfrac(bb.getLatMin(), 6)));
    bbElem.addContent(new Element("north").addContent(ucar.unidata.util.Format.dfrac(bb.getLatMax(), 6)));
    return bbElem;
  }
```

There are two ways that I see to handle this:

- add/subtract a small offset (as you suggest), which I think based on the code above, would be 10^-6.
- recognize that this is an NCSS form for a single station, and disable spatial subsetting in the form all together.


The first is much easier to implement, and does not break any current behavior, so I'm inclined to go with it.

Does anyone see any issue with adding a small delta, based on what is being passed into `ucar.unidata.util.Format.dfrac`?

**Comment by dopplershift** [comment]
Feels like there should be something more rigorous, but I'm not sure what that is at the moment.

**Comment by kerfoot** [comment]
Is there a downside to Sean's recommendation?  

Or just setting the bounding box to N:90, S:-90, E:180, W: -180?  

That would ensure that the default request contains all of the data.  If users want to subset, I think we'd assume that they know something about the location of the platform and would set the bounding box to the appropriate ranges.

**Comment by cwardgar** [comment]
I like Sean's recommendation. I see having the initial bounding box set to the (approximate) extent of the data to be a feature, and we should try to keep it in.

**Comment by dopplershift** [comment]
Seems like this might be fixed if in the process of going to 6 decimal places (from a double), we rounded in the proper direction. Adding a fudge might be easier, but it was bugging me that I hadn't (until now) come up with what seems correct mathematically.

The problem comes from the fact that truncating shrinks the domain from what it really is.

**Comment by lesserwhirls** [comment]
Yeah, that's why I thought adding a fudge factor, based on the number of decimal places, to "expand" the bounds would be ok. It's essentially rounding such that the bbox slightly expands to cover any issue with the truncation. We would need to check to make sure we don't go outside of 0-360, but I think it will work. Also, I would only do this in the Point NCSS form, not grid or grid as point.
