### ISSUE TITLE
NCSS 404 on 5.0

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#487]
No idea why this is returning a 404:

http://thredds-jumbo.unidata.ucar.edu/thredds/ncss/grib/HRRR/CONUS_3km/wrfprs/Best/dataset.html

Opendap and CDMRemote work fine (at least superficially).

**Comment by JohnLCaron** [comment]
Could someone tar up the gbx9 and ncx4 files from

/data/ldm/pub/native/grid/NOAA_GSD/HRRR/CONUS_3km/wrfprs/*

and make them avail?
thanks

**Comment by JohnLCaron** [comment]
OK the problem here is the old catalog in TdsConfig:

threddsTest/modelsHrrr.xml

it has an out-of date service element for ncss.

suggest that you use the default service, like in idd.

might want to search all the catalogs for <service> elements. I _think_ one can always use defaults for feature collections. If not, maybe we should fix.

datasetScan will still need a serviceName and service to refer to, though you could consolidate all services that are used in the top catalog, now called "global" services becasue they are accessible from any other catalog.

we can go over these thursday if needed.

**Comment by cwardgar** [comment]
This is (was?) an issue with TdsConfig, not THREDDS. We have an issue for it there: https://github.com/Unidata/TdsConfig/issues/29
