### ISSUE TITLE
.OIS data not being read properly

### ISSUE THREAD

**Issue by alanpaulkwan** [Unidata/thredds#492]
Here is an example dataset.

https://www.dropbox.com/s/ri24oz6h1rxl7on/F12199501290001.OIS?dl=0

Here is a link to the issue: http://stackoverflow.com/questions/35929150/using-ucar-iosp-to-read-a-dataset/36069839#36069839

It complains when I run the following line that it was not a valid CDM file, even though one of the hallmark examples of this IOSP is its use on the .OIS data. I happen to need the .OIS data so would really appreciate if any suggestions for fixing it! 

NetcdfFile ncfile1 = NetcdfFile.open(s);

**Comment by dopplershift** [comment]
I poked at the file, and yours seems to have (at least) one header line that the netCDF-java code isn't expecting and doesn't ignore. I'll take a look when I get a chance to see what happens if I try adding the line. If you're game for trying to run this down, the file `DMSPHeader.java` is what you're looking for.

**Comment by alanpaulkwan** [comment]
Thanks! I have no real idea how to diagnose Java - haven't used it for 10
years.

I'll make an independent effort, but I imagine even if I figured out which
line to delete is causing the problem I wouldn't know how to fix this.

**Comment by dopplershift** [comment]
#493 has code that at least lets the file be opened without errors. No idea if there are any other lurking problems.
