### ISSUE TITLE
Researching Build Breakage

### ISSUE THREAD

**Issue by devbridie** [Unidata/thredds#937]
Dear developers of the thredds project,

We are MSc students from the Delft University of Technology doing research on why builds break in open source projects. To do this, we are analyzing Travis build statistics and build history of thredds.

By analyzing the build history of thredds, we found the following:
* The project has 48% failing builds in the history
* The project has a high amount of build failures compared to other similar projects

When looking at thredds’s build metrics, we could not find clear factors that are highly correlated with this result.

To identify the reasons behind build breakage, we would like to collect developer insights into the reasons why build breakage occurs. If you have five minutes, please answer the [survey](https://www.surveymonkey.com/r/PQ7XTGM) we have created. Your response will be very useful in our study.

Thank you.

**Comment by lesserwhirls** [comment]
Greetings @devbridie!

Aree you basing your statistics off of TravisCI builds? If so, it's important to note that our config for travis was incomplete (that is, a work in progress) for quite some time, and so the builds would fail. We also have a binary dependency we ship in our git repository for use on Travis, and there were some incompatibilities with that lib and updates to the Travis OS environment. Due to this, we had several failing builds in which it was not clear why they were failing.

Cheers!
