### ISSUE TITLE
Prospects for S3, HDFS branch?

### ISSUE THREAD

**Issue by jamesmcclain** [Unidata/thredds#995]
Hello,

Some time ago, I contributed a branch to add [S3 and HDFS support](https://github.com/Unidata/thredds/tree/feature/s3%2Bhdfs).  It was decided at the time that it could not be merged until some other changes were made due to the increase in artifact size.  I am writing to ask what the prospects are for inclusion in 2018?

I am concerned because the group that I am in is still relying on that old branch, but recently that branch stopped compiling due to some published artifacts moving around.  The following changes addressed that
```diff
diff -ru thredds-feature-s3-hdfs/gradle/any/dependencies.gradle /home/jmcclain/local/src/geopyspark-netcdf/thredds-feature-s3-hdfs/gradle/any/dependencies.gradle
--- a/thredds-feature-s3-hdfs/gradle/any/dependencies.gradle	2017-05-30 16:56:04.000000000 -0400
+++ b/thredds-feature-s3-hdfs/gradle/any/dependencies.gradle	2017-12-18 08:40:46.955972235 -0500
@@ -11,7 +11,7 @@
     jcenter()
     mavenCentral()  // JCenter isn't quite a superset of Maven Central.
     maven {
-        url "https://artifacts.unidata.ucar.edu/content/repositories/unidata"
+        url "https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/"
     }
     maven {
         url "https://artifacts.unidata.ucar.edu/content/repositories/unidata-3rdparty/"
@@ -241,7 +241,7 @@
 
 libraries["gwt-dev"] = "com.google.gwt:gwt-dev:${versions["gwt"]}"
 
-libraries["threddsIso"] = "EDS:threddsIso:2.3.0-SNAPSHOT"
+libraries["threddsIso"] = "EDS:threddsIso:2.3.1"
 
 libraries["Saxon-HE"] = "net.sf.saxon:Saxon-HE:9.7.0-8"
 
```
but I am afraid that this is going to become an ongoing and worsening problem.

Thank you.

**Comment by cwardgar** [comment]
Hi James,

In order to include your contribution in mainline without bloating the default thredds.war distribution, we would need to develop a proper plugin mechanism, and modularize the project to make use of it. Unfortunately, splitting the thredds monolith would (likely) be a _monumental_ amount of work, due to the tight coupling of many components. The prospects of that work getting done in 2018 – given our current resources – are ... slim.

However, as a bandaid, we can simply periodically merge our development branch into `Unidata:feature/s3+hdfs` to stop it from getting hopelessly out-of-date. I've gone ahead and done that: https://github.com/Unidata/thredds/commit/87322e5f034be2f1e14218b599ffec3cffad2096. If you'd like me to do it again in the future, just let me know.

**Comment by jamesmcclain** [comment]
Okay, thank you.
